### ISSUE TITLE
是否有计划支持 Firefox webextension ？

### ISSUE THREAD

**Issue by ivysrono** [dangoakachan/copybetter#10]
其 API 应该与 Chrome 极为相似。
现有扩展即使搭配起来，与 CopyBetter 也相去甚远。

**Comment by dangoakachan** [comment]
抱歉，平时不接触 Firefox，没有支持的计划。

**Comment by gloomy-ghost** [comment]
@dangoakachan 再过段时间 Fx 把大部分开发完成之后把目前正在使用的已废弃 API 换成新的就行，方便的话加个 License 之后我试试做适配

**Comment by dangoakachan** [comment]
@gloomy-ghost 需要我做什么吗 ：）

**Comment by gloomy-ghost** [comment]
在 choosealicense.com 选一个协议加到这个 repo 的根目录下作为开源许可，这样如果有人想要进行改进也放得开手脚干活 😄

**Comment by dangoakachan** [comment]
@gloomy-ghost done

https://github.com/dangoakachan/copybetter/blob/master/LICENSE.txt

**Comment by gloomy-ghost** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1197451#c37

**Comment by yfdyh000** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1272869.
