### ISSUE TITLE
Spelling Error in Settings in Chrome

### ISSUE THREAD

**Issue by NoSkillzEngineer26** [dangoakachan/copybetter#12]
I took a desktop screenshot and uploaded the image to a free to use website called "postimages.org"

This is that link: https://postimg.org/image/tl1g1nil1/

When I click the plugin icon in Chrome and select "settings" this is the page that comes up.

The text says 
"Automatically opy selected text in edit box"
It should read "Automatically copy selected text in edit box"

That is all.

**Comment by dangoakachan** [comment]
Thanks
